# Generated by Django 6.0 on 2025-12-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoriy',
            new_name='Category',
        ),
    ]
